name: Deploy to Staging (GCS + CDN)

on:
  push:
    #branches: ["main"]
    workflow_dispatch: # Manual trigger 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: python build.py

      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/1070327104780/locations/global/workloadIdentityPools/static-website/providers/github-provider"
          service_account: "static-website-deployer@github-actions-111.iam.gserviceaccount.com"

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - run: |
          gsutil -m rsync -r dist gs://${{ secrets.GCS_BUCKET_STAGING }}
          gcloud compute url-maps invalidate-cdn-cache lb-for-static-website \
            --path "/*" \
            --project ${{ secrets.GCP_PROJECT_ID }}
