name: Deploy to Prod (GCS + CDN)

on:
  workflow_dispatch: # Manual trigger for production

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - run: python build.py

    - uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
        service_account: "prod-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

    - uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - run: |
        gsutil -m rsync -r dist gs://${{ secrets.GCS_BUCKET_PROD }}
        gcloud compute url-maps invalidate-cdn-cache prod-cdn-map \
          --path "/*" \
          --project ${{ secrets.GCP_PROJECT_ID }}
